# Generated by Django 4.1.1 on 2022-10-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_news_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
