# Generated by Django 4.1.1 on 2022-10-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_new_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
