# Generated by Django 4.1.1 on 2022-10-04 08:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_new_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
