# Generated by Django 4.1.1 on 2022-10-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_new_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_graduations', models.IntegerField()),
                ('number_of_professors', models.IntegerField()),
                ('number_of_housing', models.IntegerField()),
                ('number_of_students', models.IntegerField()),
            ],
        ),
    ]
