# Generated by Django 4.1.1 on 2022-10-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_workers_about_workers_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='mail',
            field=models.EmailField(default='ad@gmail.com', max_length=254),
        ),
    ]
