# Generated by Django 4.1.1 on 2022-10-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_workers_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
