# Generated by Django 4.1.1 on 2022-10-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_mail_workers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='facebook',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workers',
            name='instagram',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workers',
            name='telegram',
            field=models.CharField(default='', max_length=200),
        ),
    ]
