# Generated by Django 4.1.1 on 2022-12-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_gallery_alter_event_image_alter_new_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date_created',
            field=models.DateField(),
        ),
    ]
