# Generated by Django 4.1.1 on 2022-12-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_new_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/db/news/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('duration', models.IntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
