# Generated by Django 4.1.1 on 2022-12-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
