# Generated by Django 4.1.1 on 2022-12-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_courses_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
