# Generated by Django 4.1.1 on 2022-12-17 20:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_course_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
