# Generated by Django 4.1.1 on 2022-12-18 15:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_course_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('number', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telegram', models.CharField(default='', max_length=200)),
                ('instagram', models.CharField(default='', max_length=200)),
                ('facebook', models.CharField(default='', max_length=200)),
                ('about', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='static/db/workers/')),
            ],
        ),
    ]
