# Generated by Django 4.1.1 on 2022-12-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_leaders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Images',
        ),
    ]
