# Generated by Django 4.1.1 on 2022-12-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_gallery_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_image_for_gallery', models.ManyToManyField(to='app.images')),
            ],
        ),
    ]
