# Generated by Django 4.1.1 on 2022-12-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_gallery_select_image_for_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='select_image_for_gallery',
            field=models.ImageField(upload_to='static/db/gallery/'),
        ),
    ]
