# Generated by Django 4.1.1 on 2022-12-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_gallery_select_image_for_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='select_image_for_gallery',
            new_name='image',
        ),
    ]
