# Generated by Django 4.1.1 on 2022-12-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_select_image_for_gallery_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
